// This file is auto-generated by @hey-api/openapi-ts
import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client'
import { client } from './client.gen'
import type {
  authenticationCreateSessionData,
  authenticationCreateSessionErrors,
  authenticationCreateSessionResponses,
  authenticationLoginAccessTokenData,
  authenticationLoginAccessTokenErrors,
  authenticationLoginAccessTokenResponses,
  authenticationLogoutSessionData,
  authenticationLogoutSessionErrors,
  authenticationLogoutSessionResponses,
  authenticationRefreshSessionData,
  authenticationRefreshSessionErrors,
  authenticationRefreshSessionResponses,
  healthHealthCheckData,
  healthHealthCheckResponses,
  usersChangeCurrentUserPasswordData,
  usersChangeCurrentUserPasswordErrors,
  usersChangeCurrentUserPasswordResponses,
  usersCreateUserData,
  usersCreateUserErrors,
  usersCreateUserResponses,
  usersDeleteUserData,
  usersDeleteUserErrors,
  usersDeleteUserResponses,
  usersGetCurrentUserData,
  usersGetCurrentUserResponses,
  usersGetUserData,
  usersGetUserErrors,
  usersGetUserResponses,
  usersListUsersData,
  usersListUsersErrors,
  usersListUsersResponses,
  usersUpdateCurrentUserData,
  usersUpdateCurrentUserErrors,
  usersUpdateCurrentUserResponses,
  usersUpdateUserData,
  usersUpdateUserErrors,
  usersUpdateUserResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export class HealthService {
  /**
   * Health Check
   */
  public static healthCheck<ThrowOnError extends boolean = true>(
    options?: Options<healthHealthCheckData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      healthHealthCheckResponses,
      unknown,
      ThrowOnError
    >({
      responseType: 'json',
      url: '/api/v1/health',
      ...options,
    })
  }
}

export class AuthenticationService {
  /**
   * Create Session
   */
  public static createSession<ThrowOnError extends boolean = true>(
    options: Options<authenticationCreateSessionData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      authenticationCreateSessionResponses,
      authenticationCreateSessionErrors,
      ThrowOnError
    >({
      responseType: 'json',
      url: '/api/v1/auth/session',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

  /**
   * Refresh Session
   */
  public static refreshSession<ThrowOnError extends boolean = true>(
    options: Options<authenticationRefreshSessionData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      authenticationRefreshSessionResponses,
      authenticationRefreshSessionErrors,
      ThrowOnError
    >({
      responseType: 'json',
      url: '/api/v1/auth/session/refresh',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

  /**
   * Logout Session
   */
  public static logoutSession<ThrowOnError extends boolean = true>(
    options: Options<authenticationLogoutSessionData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      authenticationLogoutSessionResponses,
      authenticationLogoutSessionErrors,
      ThrowOnError
    >({
      url: '/api/v1/auth/session/logout',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

  /**
   * Login Access Token
   */
  public static loginAccessToken<ThrowOnError extends boolean = true>(
    options: Options<authenticationLoginAccessTokenData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      authenticationLoginAccessTokenResponses,
      authenticationLoginAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      responseType: 'json',
      url: '/api/v1/auth/login/access-token',
      ...options,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers,
      },
    })
  }
}

export class UsersService {
  /**
   * Get Current User
   */
  public static getCurrentUser<ThrowOnError extends boolean = true>(
    options?: Options<usersGetCurrentUserData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      usersGetCurrentUserResponses,
      unknown,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/me',
      ...options,
    })
  }

  /**
   * Update Current User
   */
  public static updateCurrentUser<ThrowOnError extends boolean = true>(
    options: Options<usersUpdateCurrentUserData, ThrowOnError>
  ) {
    return (options.client ?? client).put<
      usersUpdateCurrentUserResponses,
      usersUpdateCurrentUserErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/me',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

  /**
   * Change Current User Password
   */
  public static changeCurrentUserPassword<ThrowOnError extends boolean = true>(
    options: Options<usersChangeCurrentUserPasswordData, ThrowOnError>
  ) {
    return (options.client ?? client).put<
      usersChangeCurrentUserPasswordResponses,
      usersChangeCurrentUserPasswordErrors,
      ThrowOnError
    >({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/me/password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

  /**
   * List Users
   */
  public static listUsers<ThrowOnError extends boolean = true>(
    options?: Options<usersListUsersData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      usersListUsersResponses,
      usersListUsersErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users',
      ...options,
    })
  }

  /**
   * Create User
   */
  public static createUser<ThrowOnError extends boolean = true>(
    options: Options<usersCreateUserData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      usersCreateUserResponses,
      usersCreateUserErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }

  /**
   * Delete User
   */
  public static deleteUser<ThrowOnError extends boolean = true>(
    options: Options<usersDeleteUserData, ThrowOnError>
  ) {
    return (options.client ?? client).delete<
      usersDeleteUserResponses,
      usersDeleteUserErrors,
      ThrowOnError
    >({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/{userId}',
      ...options,
    })
  }

  /**
   * Get User
   */
  public static getUser<ThrowOnError extends boolean = true>(
    options: Options<usersGetUserData, ThrowOnError>
  ) {
    return (options.client ?? client).get<
      usersGetUserResponses,
      usersGetUserErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/{userId}',
      ...options,
    })
  }

  /**
   * Update User
   */
  public static updateUser<ThrowOnError extends boolean = true>(
    options: Options<usersUpdateUserData, ThrowOnError>
  ) {
    return (options.client ?? client).put<
      usersUpdateUserResponses,
      usersUpdateUserErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/{userId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })
  }
}
