// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}

/**
 * AccessTokenResponse
 */
export type AccessTokenResponse = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type?: 'bearer'
  /**
   * Expires In
   */
  expires_in: number
}

/**
 * ApiResponse[AuthTokensData]
 */
export type ApiResponse_AuthTokensData_ = {
  /**
   * Code
   */
  code?: 0
  data: AuthTokensData
  /**
   * Message
   */
  message?: 'success'
}

/**
 * ApiResponse[HealthData]
 */
export type ApiResponse_HealthData_ = {
  /**
   * Code
   */
  code?: 0
  data: HealthData
  /**
   * Message
   */
  message?: 'success'
}

/**
 * ApiResponse[PageData[UserData]]
 */
export type ApiResponse_PageData_UserData__ = {
  /**
   * Code
   */
  code?: 0
  data: PageData_UserData_
  /**
   * Message
   */
  message?: 'success'
}

/**
 * ApiResponse[UserData]
 */
export type ApiResponse_UserData_ = {
  /**
   * Code
   */
  code?: 0
  data: UserData
  /**
   * Message
   */
  message?: 'success'
}

/**
 * AuthTokensData
 */
export type AuthTokensData = {
  /**
   * Accesstoken
   */
  accessToken: string
  /**
   * Accessexpiresat
   */
  accessExpiresAt: number
  /**
   * Refreshtoken
   */
  refreshToken: string
  /**
   * Refreshexpiresat
   */
  refreshExpiresAt: number
}

/**
 * Body_authentication-login_access_token
 */
export type Body_authentication_login_access_token = {
  /**
   * Grant Type
   */
  grant_type?: string | null
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Scope
   */
  scope?: string
  /**
   * Client Id
   */
  client_id?: string | null
  /**
   * Client Secret
   */
  client_secret?: string | null
}

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * HealthData
 */
export type HealthData = {
  /**
   * Status
   */
  status: 'ok'
}

/**
 * PageData[UserData]
 */
export type PageData_UserData_ = {
  /**
   * Total
   */
  total: number
  /**
   * Items
   */
  items: Array<UserData>
  /**
   * Page
   */
  page: number
  /**
   * Pagesize
   */
  pageSize: number
}

/**
 * SessionLoginRequest
 */
export type SessionLoginRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
}

/**
 * SessionRefreshRequest
 */
export type SessionRefreshRequest = {
  /**
   * Refreshtoken
   */
  refreshToken: string
}

/**
 * UserCreateRequest
 */
export type UserCreateRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Fullname
   */
  fullName?: string | null
  /**
   * Password
   */
  password: string
  /**
   * Isactive
   */
  isActive?: boolean
  /**
   * Issuperuser
   */
  isSuperuser?: boolean
}

/**
 * UserData
 */
export type UserData = {
  /**
   * Id
   */
  id: string
  /**
   * Email
   */
  email: string
  /**
   * Fullname
   */
  fullName: string | null
  /**
   * Isactive
   */
  isActive: boolean
  /**
   * Issuperuser
   */
  isSuperuser: boolean
  /**
   * Createdat
   */
  createdAt: string
  /**
   * Updatedat
   */
  updatedAt: string
}

/**
 * UserPasswordChangeRequest
 */
export type UserPasswordChangeRequest = {
  /**
   * Currentpassword
   */
  currentPassword: string
  /**
   * Newpassword
   */
  newPassword: string
}

/**
 * UserPutRequest
 */
export type UserPutRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Fullname
   */
  fullName: string | null
  /**
   * Password
   */
  password?: string | null
  /**
   * Isactive
   */
  isActive: boolean
  /**
   * Issuperuser
   */
  isSuperuser: boolean
}

/**
 * UserSelfPutRequest
 */
export type UserSelfPutRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Fullname
   */
  fullName: string | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type healthHealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/health'
}

export type healthHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_HealthData_
}

export type healthHealthCheckResponse =
  healthHealthCheckResponses[keyof healthHealthCheckResponses]

export type authenticationCreateSessionData = {
  body: SessionLoginRequest
  path?: never
  query?: never
  url: '/api/v1/auth/session'
}

export type authenticationCreateSessionErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type authenticationCreateSessionError =
  authenticationCreateSessionErrors[keyof authenticationCreateSessionErrors]

export type authenticationCreateSessionResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_AuthTokensData_
}

export type authenticationCreateSessionResponse =
  authenticationCreateSessionResponses[keyof authenticationCreateSessionResponses]

export type authenticationRefreshSessionData = {
  body: SessionRefreshRequest
  path?: never
  query?: never
  url: '/api/v1/auth/session/refresh'
}

export type authenticationRefreshSessionErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type authenticationRefreshSessionError =
  authenticationRefreshSessionErrors[keyof authenticationRefreshSessionErrors]

export type authenticationRefreshSessionResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_AuthTokensData_
}

export type authenticationRefreshSessionResponse =
  authenticationRefreshSessionResponses[keyof authenticationRefreshSessionResponses]

export type authenticationLogoutSessionData = {
  body: SessionRefreshRequest
  path?: never
  query?: never
  url: '/api/v1/auth/session/logout'
}

export type authenticationLogoutSessionErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type authenticationLogoutSessionError =
  authenticationLogoutSessionErrors[keyof authenticationLogoutSessionErrors]

export type authenticationLogoutSessionResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type authenticationLogoutSessionResponse =
  authenticationLogoutSessionResponses[keyof authenticationLogoutSessionResponses]

export type authenticationLoginAccessTokenData = {
  body: Body_authentication_login_access_token
  path?: never
  query?: never
  url: '/api/v1/auth/login/access-token'
}

export type authenticationLoginAccessTokenErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type authenticationLoginAccessTokenError =
  authenticationLoginAccessTokenErrors[keyof authenticationLoginAccessTokenErrors]

export type authenticationLoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessTokenResponse
}

export type authenticationLoginAccessTokenResponse =
  authenticationLoginAccessTokenResponses[keyof authenticationLoginAccessTokenResponses]

export type usersGetCurrentUserData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type usersGetCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_UserData_
}

export type usersGetCurrentUserResponse =
  usersGetCurrentUserResponses[keyof usersGetCurrentUserResponses]

export type usersUpdateCurrentUserData = {
  body: UserSelfPutRequest
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type usersUpdateCurrentUserErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersUpdateCurrentUserError =
  usersUpdateCurrentUserErrors[keyof usersUpdateCurrentUserErrors]

export type usersUpdateCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_UserData_
}

export type usersUpdateCurrentUserResponse =
  usersUpdateCurrentUserResponses[keyof usersUpdateCurrentUserResponses]

export type usersChangeCurrentUserPasswordData = {
  body: UserPasswordChangeRequest
  path?: never
  query?: never
  url: '/api/v1/users/me/password'
}

export type usersChangeCurrentUserPasswordErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersChangeCurrentUserPasswordError =
  usersChangeCurrentUserPasswordErrors[keyof usersChangeCurrentUserPasswordErrors]

export type usersChangeCurrentUserPasswordResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type usersChangeCurrentUserPasswordResponse =
  usersChangeCurrentUserPasswordResponses[keyof usersChangeCurrentUserPasswordResponses]

export type usersListUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Pagesize
     */
    pageSize?: number
  }
  url: '/api/v1/users'
}

export type usersListUsersErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersListUsersError =
  usersListUsersErrors[keyof usersListUsersErrors]

export type usersListUsersResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_PageData_UserData__
}

export type usersListUsersResponse =
  usersListUsersResponses[keyof usersListUsersResponses]

export type usersCreateUserData = {
  body: UserCreateRequest
  path?: never
  query?: never
  url: '/api/v1/users'
}

export type usersCreateUserErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersCreateUserError =
  usersCreateUserErrors[keyof usersCreateUserErrors]

export type usersCreateUserResponses = {
  /**
   * Successful Response
   */
  201: ApiResponse_UserData_
}

export type usersCreateUserResponse =
  usersCreateUserResponses[keyof usersCreateUserResponses]

export type usersDeleteUserData = {
  body?: never
  path: {
    /**
     * Userid
     */
    userId: string
  }
  query?: never
  url: '/api/v1/users/{userId}'
}

export type usersDeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersDeleteUserError =
  usersDeleteUserErrors[keyof usersDeleteUserErrors]

export type usersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type usersDeleteUserResponse =
  usersDeleteUserResponses[keyof usersDeleteUserResponses]

export type usersGetUserData = {
  body?: never
  path: {
    /**
     * Userid
     */
    userId: string
  }
  query?: never
  url: '/api/v1/users/{userId}'
}

export type usersGetUserErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersGetUserError = usersGetUserErrors[keyof usersGetUserErrors]

export type usersGetUserResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_UserData_
}

export type usersGetUserResponse =
  usersGetUserResponses[keyof usersGetUserResponses]

export type usersUpdateUserData = {
  body: UserPutRequest
  path: {
    /**
     * Userid
     */
    userId: string
  }
  query?: never
  url: '/api/v1/users/{userId}'
}

export type usersUpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HTTPValidationError
}

export type usersUpdateUserError =
  usersUpdateUserErrors[keyof usersUpdateUserErrors]

export type usersUpdateUserResponses = {
  /**
   * Successful Response
   */
  200: ApiResponse_UserData_
}

export type usersUpdateUserResponse =
  usersUpdateUserResponses[keyof usersUpdateUserResponses]
